version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    stdin_open: true
    tty: true

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./docker-compose/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/var/www/frontend
      - ./backend:/var/www/backend
    depends_on:
      - frontend
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'notes_app'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
