version: '3.8'

services:
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - '8080'
    environment:
      - HOST=localhost
      - PORT=8080
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    networks:
      - cicd

  backend:
    container_name: backend
    build:
      args:
        user: David
        uid: 1000
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www
    ports:
      - '9000:9000'
    environment:
      - SERVICE_PORT=9000
    networks:
      - cicd

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'notes_app'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - cicd

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    networks:
      - cicd

networks:
  cicd:
    driver: bridge

volumes:
  mysql_data:
