apiVersion: v1
kind: Service
metadata:
  name: cicd-project-backend-service
  namespace: cicd-project
spec:
  selector:
    app: cicd-project-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
