apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-project-backend-deployment
  namespace: cicd-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cicd-project-backend-deployment
  template:
    metadata:
      labels:
        app: cicd-project-backend-deployment
    spec:
      containers:
        - name: cicd-project-backend-deployment
          image: lulata/cicd-backend:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_DATABASE
              value: "notes_app"
            - name: DB_USERNAME
              value: "root"
            - name: DB_PASSWORD
              value: ""
          volumeMounts:
            - name: config-volume
              mountPath: /var/www/backend
      volumes:
        - name: config-volume
          configMap:
            name: cicd-project-backend-config
            items:
              - key: APPSETTINGS_JSON
                path: appsettings.json
